name: CI

on:
  push:
  pull_request:

jobs:
  gha-cache:
    name: Build CI container - gha cache
    runs-on: ubuntu-latest
    steps:
      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Install Build X"
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug

      - name: "Build docker image - base"
        uses: docker/build-push-action@v2
        with:
          target: base
          push: false
          cache-from: type=gha,scope=base
          cache-to: type=gha,mode=max,scope=base

      - name: "Build docker image - prod"
        uses: docker/build-push-action@v2
        with:
          target: prod
          tags: ghcr.io/bendavies/docker-build-cache-limits:prod
          push: true
          cache-from: |
            type=gha,scope=base
            type=gha,scope=prod
          cache-to: type=gha,mode=max,scope=prod

  local-cache:
    name: Build CI container - local cache
    runs-on: ubuntu-latest
    steps:
      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Install Build X"
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug

      - name: "Cache Docker layers - base"
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache-base
          key: ${{ runner.os }}-buildx-base-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-base-

      - name: "Cache Docker layers - prod"
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache-prod
          key: ${{ runner.os }}-buildx-prod-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-prod-

      - name: "Build docker image - base"
        uses: docker/build-push-action@v2
        with:
          target: base
          push: false
          cache-from: type=local,src=/tmp/.buildx-cache-base
          cache-to: type=local,dest=/tmp/.buildx-cache-base-new

      - name: "Build docker image - prod"
        uses: docker/build-push-action@v2
        with:
          target: prod
          tags: ghcr.io/bendavies/docker-build-cache-limits:prod
          push: true
          cache-from: |
            type=local,src=/tmp/.buildx-cache-base-new
            type=local,src=/tmp/.buildx-cache-prod
          cache-to: type=local,dest=/tmp/.buildx-cache-prod-new

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache - base
        run: |
          rm -rf /tmp/.buildx-cache-base
          mv /tmp/.buildx-cache-base-new /tmp/.buildx-cache-base

      - name: Move cache - prod
        run: |
          rm -rf /tmp/.buildx-cache-prod
          mv /tmp/.buildx-cache-prod-new /tmp/.buildx-cache-prod