name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    name: Build CI container
    runs-on: ubuntu-latest
    steps:
      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Install Build X"
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug

      - name: "Build docker image - base"
        uses: docker/build-push-action@v2
        with:
          target: base
          push: false
          cache-from: type=gha,scope=base
          cache-to: type=gha,mode=max,scope=base

      - name: "Build docker image - prod"
        uses: docker/build-push-action@v2
        with:
          target: prod
          tags: ghcr.io/bendavies/docker-build-cache-limits:prod
          push: true
          cache-from: |
            type=gha,scope=base
            type=gha,scope=prod
          cache-to: type=gha,mode=max,scope=prod